modLoader="javafml"
loaderVersion="[32,)"
[[mods]]
modId="drawerstooltip"
version="${file.jarVersion}"
displayName="Drawers Tooltip"
authors="Snownee"
displayURL="https://www.curseforge.com/minecraft/mc-mods/drawers-tooltip"
description=""
