modLoader="javafml"
loaderVersion="[38,)"
license="MIT"

[[mods]]
modId="drawerstooltip"
version="${file.jarVersion}"
displayName="Drawers Tooltip"
authors="Snownee"
displayURL="https://www.curseforge.com/minecraft/mc-mods/drawers-tooltip"
description=""

[[dependencies.drawerstooltip]]
    modId="storagedrawers"
    mandatory=true
    versionRange="*"
